apiVersion: apps/v1
kind: Deployment
metadata:
  name: large-dataset-server
  namespace: default
  labels:
    app: large-dataset-server
    version: v1
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: large-dataset-server
  template:
    metadata:
      labels:
        app: large-dataset-server
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: large-dataset-server
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: server
        image: large-dataset-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        env:
        - name: CONFIG_PATH
          value: "/configs/production.yaml"
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: large-dataset-config
              key: kafka-brokers
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: large-dataset-secrets
              key: jwt-secret
        - name: ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: large-dataset-config
              key: allowed-origins
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /configs
          readOnly: true
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: config
        configMap:
          name: large-dataset-config-files
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: large-dataset-server
  namespace: default 